"""Extension → language mapping for repository snapshots."""

EXT_LANGUAGE = {
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JSX",
    ".ts": "TypeScript",
    ".tsx": "TSX",
    ".py": "Python",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".hpp": "C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".scala": "Scala",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".less": "LESS",
    ".json": "JSON",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".toml": "TOML",
    ".ini": "INI",
    ".conf": "Config",
    ".md": "Markdown",
    ".markdown": "Markdown",
    ".rst": "reStructuredText",
    ".sql": "SQL",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".fish": "Shell",
    ".ps1": "PowerShell",
    ".bat": "Batch",
    ".cmd": "Batch",
    ".dockerfile": "Dockerfile",
    "dockerfile": "Dockerfile",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".xml": "XML",
    ".svg": "XML",
    ".proto": "Protocol Buffers",
    ".graphql": "GraphQL",
    ".gql": "GraphQL",
    ".lua": "Lua",
    ".r": "R",
    ".dart": "Dart",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".hs": "Haskell",
    ".zig": "Zig",
    ".nim": "Nim",
    ".clj": "Clojure",
    ".coffee": "CoffeeScript",
    ".mk": "Makefile",
    "makefile": "Makefile",
    "gemfile": "Ruby",
}


def language_for(path: str) -> str | None:
    name = path.rsplit("/", 1)[-1].lower()
    if name in EXT_LANGUAGE:
        return EXT_LANGUAGE[name]
    dot = name.rfind(".")
    if dot > 0:
        return EXT_LANGUAGE.get(name[dot:])
    return None
